language: node_js
node_js:
  - "6"
before_install:
  # virtual frame buffer for headless browsers
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
before_script:
  - make build
script:
  - hack/verify-dist.sh
  - grunt test-unit
  # - grunt test-integration --browser=chrome can't since we don't install oc in travis
