language: node_js
node_js:
  - "6"
addons:
  chrome: stable
before_script:
  - make build
  - node ./node_modules/protractor/bin/webdriver-manager update
  # FIXME: figure out if xvfb or chrome-headless is best
  # - https://docs.travis-ci.com/user/gui-and-headless-browsers/
  #
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  # - sleep 3 # give xvfb some time to start
  #
# setting up google-chrome-stable is before_install, not before_script  
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  # check the dist before running all the tests to save time
  - hack/verify-dist.sh
  - grunt test-unit
  - grunt test-integration
