language: node_js
node_js:
  - "6"
addons:
  chrome: stable
before_script:
  - make build
  # FIXME:
  # This needs to be enabled again when we eliminate PhantomJS for Firefox
  # Even the unit tests require a browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  # check the dist before running all the tests to save time
  - hack/verify-dist.sh
  - grunt test-unit
  - grunt test-integration
