language: node_js
node_js:
  - "6"
before_install:
  # virtual frame buffer for headless browsers
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
before_script:
  - make build
script:
  - hack/verify-dist.sh
  - grunt test-unit
  # There is no server running in travis, therefore
  # we cannot run the e2e tests.
  # - grunt test-integration --browser=chrome
